///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class R {
  R._();

  static const String img1 = 'assets/image/img1.png';
  static const String img2 = 'assets/image/img2.png';
  static const String img3 = 'assets/image/img3.png';
}
